### ISSUE TITLE
测试上传 ipa 包出现问题

### ISSUE THREAD

**Issue by ziiip** [getzealot/zealot#112]
已经用 docker 的方式成功运行了，但在使用过程中出现了问题
在示例应用中，上传 ipa 包，会出现错误
<img width="573" alt="image" src="https://user-images.githubusercontent.com/8551909/72079363-bc150980-3335-11ea-8e8f-faf93c1256b0.png">

日志在响应时间显示：
``` shell
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25] Started GET "/channels/4aqlW/releases/upload" for 172.20.0.1 at 2020-01-09 22:55:26 +0800
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25] Processing by ReleasesController#new as HTML
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25]   Parameters: {"channel_id"=>"4aqlW"}
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25]   Rendering releases/new.html.slim within layouts/application
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25]   Rendered releases/_form.html.slim (Duration: 35.7ms | Allocations: 15479)
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25]   Rendered releases/new.html.slim within layouts/application (Duration: 66.8ms | Allocations: 33696)
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25]   Rendered layouts/_tips.html.slim (Duration: 3.1ms | Allocations: 2710)
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25]   Rendered layouts/_main_sidebar.html.slim (Duration: 12.3ms | Allocations: 25940)
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25]   Rendered layouts/_navigation.html.slim (Duration: 20.8ms | Allocations: 36124)
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25]   Rendered layouts/_content_header.html.slim (Duration: 5.8ms | Allocations: 4822)
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25]   Rendered layouts/_messages.html.slim (Duration: 7.5ms | Allocations: 3786)
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25]   Rendered layouts/_content.html.slim (Duration: 23.6ms | Allocations: 11336)
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25]   Rendered layouts/_footer.html.slim (Duration: 8.5ms | Allocations: 4019)
zealot_1    | [f52bb5cd-ab3d-4fcf-83e9-859eb4dd6d25] Completed 200 OK in 246ms (Views: 130.3ms | ActiveRecord: 35.1ms | Allocations: 137610)
zealot_1    | [0356689e-1b53-41d4-9a14-03ecc2d510ff] Started POST "/channels/4aqlW/releases" for 172.20.0.1 at 2020-01-09 22:55:35 +0800
zealot_1    | [0356689e-1b53-41d4-9a14-03ecc2d510ff] Processing by ReleasesController#create as HTML
zealot_1    | [0356689e-1b53-41d4-9a14-03ecc2d510ff]   Parameters: {"authenticity_token"=>"zixiosZN+WDuK9lBJgYzVEqfRve3K5LD6IsDHgnAnB8IInK+lazhgr5ZsxhjlUJKiDaM2GaEVbeKngYSLNQH7w==", "release"=>{"file"=>#<ActionDispatch::Http::UploadedFile:0x0000558cd0eb54f8 @tempfile=#<Tempfile:/tmp/RackMultipart20200109-46-1lalhiy.ipa>, @original_filename="cb.ipa", @content_type="application/octet-stream", @headers="Content-Disposition: form-data; name=\"release[file]\"; filename=\"cb.ipa\"\r\nContent-Type: application/octet-stream\r\n">, "changelog"=>"", "release_type"=>"", "branch"=>"", "git_commit"=>"", "ci_url"=>""}, "commit"=>"上传应用", "channel_id"=>"4aqlW"}
zealot_1    | [0356689e-1b53-41d4-9a14-03ecc2d510ff] Completed 500 Internal Server Error in 2916ms (ActiveRecord: 1.4ms | Allocations: 162993)
zealot_1    | [0356689e-1b53-41d4-9a14-03ecc2d510ff]   
zealot_1    | [0356689e-1b53-41d4-9a14-03ecc2d510ff] NameError (undefined local variable or method `device' for #<Class:0x0000558ccce36698>
zealot_1    | Did you mean?  devise):
zealot_1    | [0356689e-1b53-41d4-9a14-03ecc2d510ff]   
zealot_1    | [0356689e-1b53-41d4-9a14-03ecc2d510ff] app/models/release.rb:53:in `block in upload_file'
zealot_1    | [0356689e-1b53-41d4-9a14-03ecc2d510ff] app/models/release.rb:37:in `upload_file'
zealot_1    | [0356689e-1b53-41d4-9a14-03ecc2d510ff] app/controllers/releases_controller.rb:26:in `create'
```

麻烦帮助一下，谢谢。

**Comment by icyleaf** [comment]
感谢反馈，已经修复，在 zealot-docker 目录下执行：

```sh
docker-compose down
docker-compose pull
docker-compose up -d
```

可能重新拉取在运行时遇到 zealot 运行有问题可能是外部 volume 没有同步最新容器的代码，需要：

```sh
docker-compose down
docker volume rm zealot-data
docker volume create zealot-data
docker-compose up -d
``` 

这个问题我再看怎么解决。

**Comment by ziiip** [comment]
已经尝试了，两批命令过后，可以上传应用了。感谢

**Comment by icyleaf** [comment]
欢迎反馈任何问题和想法。

顺便问下，你是通过什么渠道得知 zealot 的？我还没开始宣传呢  :D

**Comment by ziiip** [comment]
Github 搜出来的。刚好有需求。可以说，这个 repo 超级棒。感谢你们的付出
